[tool.poetry]
name = "backend-kurs-practice"
version = "0.1.0"
description = ""
authors = ["alexander111222-max <shurak26@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
